/**
 * Automatically generated types for motia
 * Do NOT edit this file manually.
 * 
 * Consider adding this file to .prettierignore and eslint ignore.
 */
import { EventHandler, ApiRouteHandler, ApiResponse, MotiaStream, CronHandler } from 'motia'

declare module 'motia' {
  interface FlowContextStateStreams {
    
  }

  interface Handlers {
    'TsUpdatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'ts.pet.status.update.requested'; data: never }>
    'TsSetNextFeedingReminder': EventHandler<never, { topic: 'ts.feeding.reminder.completed'; data: never }>
    'TsPetEnrichment': EventHandler<never, never>
    'TsPetLifecycleOrchestrator': EventHandler<never, never>
    'TsListPets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TsGetPet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TsDeletionReaper': CronHandler<never>
    'TsDeletePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'TsCreatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'ts.pet.created'; data: never } | { topic: 'ts.feeding.reminder.enqueued'; data: never }>
    'PyUpdatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'py.pet.status.update.requested'; data: never }>
    'PySetNextFeedingReminder': EventHandler<never, { topic: 'py.feeding.reminder.completed'; data: never }>
    'PyPetLifecycleOrchestrator': EventHandler<never, never>
    'PyListPets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'PyGetPet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'PyDeletionReaper': CronHandler<never>
    'PyDeletePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'PyCreatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'py.pet.created'; data: never } | { topic: 'py.feeding.reminder.enqueued'; data: never }>
    'JsUpdatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'js.pet.status.update.requested'; data: never }>
    'JsSetNextFeedingReminder': EventHandler<never, { topic: 'js.feeding.reminder.completed'; data: never }>
    'JsPetLifecycleOrchestrator': EventHandler<never, never>
    'JsListPets': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'JsGetPet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'JsDeletionReaper': CronHandler<never>
    'JsDeletePet': ApiRouteHandler<Record<string, unknown>, unknown, never>
    'JsCreatePet': ApiRouteHandler<Record<string, unknown>, unknown, { topic: 'js.pet.created'; data: never } | { topic: 'js.feeding.reminder.enqueued'; data: never }>
  }
}